<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<Authors>Curate Coders Ltd t/a BuiltForYou Digital: Mike Chadwick, Jamie Howarth</Authors>
		<Company>Curate Coders Ltd</Company>
		<Description>Helper classes &amp; methods to create responsive image URLs for Umbraco website developers running CloudFlare Pro</Description>
		<Copyright>2025 Curate Coders Ltd. All rights reserved.</Copyright>
		<PackageProjectUrl>https://github.com/CurateCoders/CurateCoders.CloudFlarePro</PackageProjectUrl>
		<RepositoryUrl>https://github.com/CurateCoders/CurateCoders.CloudFlarePro</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>C# Umbraco Razor CloudFlare CloudFlarePro responsive images</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Version>13.12.1</Version>
	</PropertyGroup>
	<ItemGroup>
	  <Content Include="Views\Shared\_ExamplePartialView.cshtml" />
	  <Content Include="Views\_ExampleViewNew.cshtml" />
	  <Content Include="Views\_ExampleView.cshtml" />
	  <None Include="..\..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Umbraco.Cms.Web.Common" Version="13.12.1" />
	</ItemGroup>
</Project>
